resources:
  pipelines:
    pipeline_iedr_pipeline:
      name: IEDR Pipeline
      configuration:
        catalog: ${var.catalog}
        table_list: ['circuits', 'planned_der', 'install_der']
        utility_list: ['utility1', 'utility2']
      libraries:
        - glob:
            include: ../../src/pipelines/IEDR_Pipeline/transformations/**
      schema: silver
      continuous: false
      development: false
      photon: true
      channel: CURRENT
      catalog: iedr
      serverless: true
      root_path: ../../src/pipelines/IEDR_Pipeline
